function_overloading: function_overloading.o
	g++ -o function_overloading function_overloading.o
function_overloading.o: function_overloading.cpp
	g++ -c function_overloading.cpp
clean:
	rm function_overloading.o
