array_struct_person: array_struct_person.o
	g++ -o array_struct_person array_struct_person.o
array_struct_person.o: array_struct_person.c
	g++ -c array_struct_person.c
clean:
	rm array_struct_person.o

